services:
  qdrant:
    build:
      context: ./ssom_qdrant # 커스텀된 qdrant 이미지
      dockerfile: Dockerfile
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 20

  fastapi-server:
    build:
      context: ./ssom_server
      dockerfile: Dockerfile
    container_name: ssom-llm
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - RETRIEVER_TOP_K=${RETRIEVER_TOP_K}
      - COLLECTION_NAME=${COLLECTION_NAME}
    volumes:
      - ./github_repo:/app/github_repo

volumes:
  qdrant_storage:
